"""Release scribe — release notes from commits, as a draft release.

Autonomy: L2_PROPOSE. Low risk, high toil: the notes are generated from the
commit list, grouped by conventional-commit type, and published as a *draft*
release for a human to publish.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from regent.agents.base import Agent, AgentOutput, CheckResult, expect
from regent.core.models import DataClass, RiskClass
from regent.runtime.context import RunContext

SECTIONS = ("breaking", "features", "fixes", "security", "other")


class NotesOutput(AgentOutput):
    """Release notes."""

    version: str = ""
    breaking: list[str] = Field(default_factory=list)
    features: list[str] = Field(default_factory=list)
    fixes: list[str] = Field(default_factory=list)
    security: list[str] = Field(default_factory=list)
    other: list[str] = Field(default_factory=list)


class ReleaseScribe(Agent):
    """Writes release notes and drafts the release."""

    name: ClassVar[str] = "release-scribe"
    description: ClassVar[str] = "Generate release notes from commits and draft the GitHub release"
    default_tier: ClassVar[str] = "fast"
    default_skills: ClassVar[tuple[str, ...]] = ("conventional-commits",)
    highest_risk: ClassVar[RiskClass] = RiskClass.PROPOSE
    output_type: ClassVar[type[AgentOutput]] = NotesOutput

    def analyse(self, ctx: RunContext) -> AgentOutput:
        """Compare two refs and write the notes."""
        base = str(ctx.trigger.payload["base"])
        head = str(ctx.trigger.payload["head"])
        compared = ctx.tool("github.compare", base=base, head=head)
        if not compared.ok:
            raise RuntimeError(f"could not compare {base}...{head}: {compared.error}")
        commits = compared.output["commits"]
        self._commit_count = len(commits)
        listing = (
            "\n".join(f"- {c['sha']} {c['message'].splitlines()[0]}" for c in commits)
            or "(no commits)"
        )
        user = f"Release {head} (previous: {base}), {len(commits)} commit(s).\n\n" + ctx.untrusted(
            "commits", listing, DataClass.INTERNAL
        )
        completion = ctx.llm(
            "release_scribe",
            values={"repository": ctx.repository},
            user=user,
            schema=self.output_schema(),
            effort="low",
        )
        if completion.parsed is None:
            raise RuntimeError("the model returned no structured notes")
        output = NotesOutput.model_validate(completion.parsed)
        output.version = output.version or head
        return output

    def checks(self, output: AgentOutput, ctx: RunContext) -> list[CheckResult]:  # noqa: ARG002
        """Cannot describe more changes than there were commits."""
        output = expect(output, NotesOutput)
        total = sum(len(getattr(output, s)) for s in SECTIONS)
        commits = getattr(self, "_commit_count", 0)
        return [
            CheckResult(
                check="notes_not_longer_than_history",
                passed=total <= max(commits, 1),
                detail=f"{total} lines for {commits} commits",
            )
        ]

    def act(self, output: AgentOutput, ctx: RunContext) -> dict[str, Any]:
        """Create the draft release."""
        output = expect(output, NotesOutput)
        created = ctx.tool(
            "github.create_release",
            tag=output.version,
            name=output.version,
            body=render_notes(output),
            draft=True,
        )
        return {"release": created.output}


def render_notes(output: NotesOutput) -> str:
    """Markdown release notes."""
    titles = {
        "breaking": "⚠️ Breaking changes",
        "features": "✨ Features",
        "fixes": "🐛 Fixes",
        "security": "🔒 Security",
        "other": "🧹 Other",
    }
    lines = [f"# {output.version}", "", output.summary, ""]
    for section in SECTIONS:
        items = getattr(output, section)
        if items:
            lines += [f"## {titles[section]}", *(f"- {item}" for item in items), ""]
    lines.append("<sub>Draft generated by Regent release-scribe from the commit history.</sub>")
    return "\n".join(lines)
