apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: regent
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: regent
  minReplicas: 2
  maxReplicas: 6
